workflows:
  version: 2
  main:
    jobs:
    - build-prod:
        filters:
          branches:
            only: master

version: 2
jobs:
  build-prod:
    machine: true
    steps:
    - checkout
    - run:
        name: blah
        command: |
          echo hi





